import 'dart:convert';
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';


class TableQRCode extends StatefulWidget {
  var storeName,image;
  TableQRCode(this.storeName,this.image);

  @override
  _PDFLaoutState createState() => _PDFLaoutState();
}

class _PDFLaoutState extends State<TableQRCode> {
  var pdf = pw.Document;
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,

      home: Scaffold(
        appBar: AppBar(title: Text("Table QRCode")),
        body: PdfPreview(
          allowSharing: true,
          allowPrinting: true,
          build: (format) => _generatePdf(format,""),
        ),
      ),
    );
  }

  Future<Uint8List> _generatePdf(PdfPageFormat format, String title) async {
    final pdf = pw.Document();
    final PdfImage img = await pdfImageFromImageProvider(pdf: pdf.document, image: MemoryImage(widget.image));
    pdf.addPage(
      pw.Page(
        pageFormat: format,
        build: (context) {
          return pw.Column(
              children: [
                pw.Padding(
                  padding: pw.EdgeInsets.only(top: 50),
                  child: pw.Column(
                      children: [
                        pw.Text("Table: "+widget.storeName,style: pw.TextStyle(fontSize:25,fontWeight: pw.FontWeight.bold)),
                        pw.Center(
                            child: pw.Image(img,width: 300,height:300)
                        ),
                        pw.Center(
                            child: pw.Text("this QRCode is Generated By ExaBistro",style: pw.TextStyle(fontSize: 25))
                        ),
                      ]
                  ),
                ),
              ]
          );
        },
      ),
    );

    return pdf.save();
  }
}